
export const DEVICE_DID_CHANGE_SIZE = 'DEVICE_DID_CHANGE_SIZE';
export const UPDATE_DATE = 'UPDATE_DATE';


//  MLB

export const GET_STANDINGS_SUCCESSFUL = 'GET_STANDINGS_SUCCESSFUL';

//  Dugout

export const GET_BOXSCORES_ATTEMPTED = 'GET_BOXSCORES_ATTEMPTED';
export const GET_BOXSCORES_SUCCESSFUL = 'GET_BOXSCORES_SUCCESSFUL';
export const GET_BOXSCORES_FAILED = 'GET_BOXSCORES_FAILED';


